name: RK4_SINDy
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.1
  - numpy=1.19.2
  - pip=20.2.2
  - python=3.8.5
  - pytorch=1.6.0
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - tikzplotlib=0.9.8
  - pip:
    - torch-optimizer==0.1.0
    - pysindy
